server:
  port: 8090
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.75.3:81 #Nacos服务注册中心地址
      -Dnacos:
        standalone: true
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: http://192.168.75.3:8080
        # 默认8719端口，键入被占用会自动从8719+1，直到找到未被占用的端口
        port: 8719

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-provider